# config/config.yaml
database:
  account: "sfsenorthamerica-demo_jrajbhushan"
  user_name: "jrajbhushan"
  password: "<pwd>"
  database_name: "aflac"
  schema_name: "public"
  stage_name: "azureiplist_stg"
  role_name: "accountadmin"
  warehouse_name: "demo_l_wh"
  network_policy: "nw_pol"


download:
  url: "https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519"
  file_path: "/Users/jrajbhushan/Desktop/secode/demos"
  
