# config/config.yaml
database:
  account: "<snowflake account name>"
  user_name: "<user name>"
  password: "<password>"
  database_name: "<database name>"
  schema_name: "<schema name>"
  stage_name: "<internal stage>"
  role_name: "accountadmin"
  warehouse_name: "<warehouse name>"
  network_policy: "<Current network policy to which you want to add the new IP addresses>"


download:
  url: "https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519"
  file_path: "<folder where you want to download the file to>"
  
